import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import SQLiteDatabase from 'better-sqlite3';
import { and, eq } from 'drizzle-orm';
import { drizzle, type BetterSQLite3Database } from 'drizzle-orm/better-sqlite3';
import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
import { readMigrationFiles } from 'drizzle-orm/migrator';
import * as schema from './db/schema.js';
import { drizzleMigrations, sqliteMaster } from './db/migrations.js';
import type { NotificationEvent } from './notifications.js';

export type ItemId = string;

export interface ShoppingItem {
  id: ItemId;
  name: string;
  amount: string;
  collected: boolean;
  createdAt: number;
  updatedAt: number;
  /** The participant who created the item. */
  by: string | null;
  /** The participant whose accepted mutation was most recent. */
  lastEditedBy: string | null;
}

export interface Member {
  clientId: string;
  name: string;
  color: string;
  joinedAt: number;
  leftAt: number | null;
}

export interface PushSubscription {
  endpoint: string;
  keys: {
    p256dh: string;
    auth: string;
  };
}

export interface PushDestination extends PushSubscription {
  listId: string;
  clientId: string;
  muted: boolean;
}

export interface ShoppingList {
  id: string;
  name: string;
  ownerToken: string;
  createdAt: number;
  clearedAt: number | null;
  /** Monotonically increasing revision of accepted list mutations. */
  revision: number;
  items: ShoppingItem[];
  members: Record<string, Member>;
}

export type OperationKind =
  | 'item:add'
  | 'item:update'
  | 'item:delete'
  | 'list:clear'
  | 'list:rename'
  | 'list:delete';

const OPERATION_KINDS: OperationKind[] = [
  'item:add', 'item:update', 'item:delete', 'list:clear', 'list:rename', 'list:delete',
];

export interface StoreOperation {
  operationId: string;
  kind: OperationKind;
  payload: Record<string, unknown>;
  actorClientId: string | null;
  actorName?: string;
  /** Current typed transports opt into strict Operation ID payload fencing. */
  protocolVersion?: number;
}

export interface OperationAck {
  t: 'ack';
  opId: string;
  status: 'accepted' | 'rejected';
  revision: number;
  reason?: string;
  reasonCode?: string;
  message?: string;
  item?: ShoppingItem;
  tempItemId?: string;
  itemId?: string;
  idMap?: { tempId: string; itemId: string };
}

export interface OperationResult {
  ack: OperationAck;
  list: ShoppingList | null;
  duplicate: boolean;
  terminal: boolean;
  notification?: NotificationEvent;
  notificationRecipients?: PushDestination[];
}

/**
 * A compatibility view of the database used by the realtime layer. The
 * source of truth is SQLite; this object is a small in-memory read cache so
 * websocket broadcasts do not need to rebuild a list for every client.
 */
interface StoreSnapshot {
  lists: Record<string, ShoppingList>;
}

interface MigrationSnapshot {
  tables: Record<string, { columns: Record<string, unknown> }>;
}

interface MigrationJournal {
  entries: Array<{ idx: number }>;
}

export interface ItemPatch {
  name?: unknown;
  amount?: unknown;
  collected?: unknown;
}

export interface NewItem {
  name?: unknown;
  amount?: unknown;
}

export const rid = (bytes = 9): string => crypto.randomBytes(bytes).toString('base64url');

/** Strip control chars, trim, and cap a user-provided string. */
export function cleanText(value: unknown, max: number): string {
  if (typeof value !== 'string') return '';
  // eslint-disable-next-line no-control-regex
  return value.replace(/[\u0000-\u001f\u007f]/g, '').trim().slice(0, max);
}

const MIGRATIONS_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'migrations');
const BOOTSTRAP_MIGRATIONS_DIR = path.join(MIGRATIONS_DIR, 'bootstrap');

const databaseSchema = { ...schema, drizzleMigrations, sqliteMaster };

/**
 * SQLite-backed persistence using Drizzle's better-sqlite3 adapter.
 *
 * Writes are committed synchronously by SQLite, which is a better fit for the
 * websocket operation stream than debounced JSON serialization. Schema
 * changes are generated by Drizzle Kit and applied from the committed
 * migrations directory at startup.
 */
export class Store {
  /** In-memory projection used by the realtime layer; SQLite remains canonical. */
  private data: StoreSnapshot = { lists: {} };
  public readonly file: string;
  private readonly sqlite: SQLiteDatabase.Database;
  private readonly db: BetterSQLite3Database<typeof databaseSchema>;
  private closed = false;

  public constructor(file: string) {
    this.file = file;

    fs.mkdirSync(path.dirname(file), { recursive: true });
    this.sqlite = new SQLiteDatabase(file);
    this.sqlite.pragma('foreign_keys = ON');
    this.sqlite.pragma('journal_mode = WAL');
    this.db = drizzle(this.sqlite, { schema: databaseSchema });
    this.applyMigrations();
    this.cleanupProcessedOperations();
    this.load();
  }

  /**
   * Apply committed Drizzle Kit migrations and adopt databases created before
   * the migration journal existed. Adoption only records the migrations that
   * the physical schema already contains; the normal migrator then applies the
   * remaining migrations.
   */
  private applyMigrations(): void {
    const catalog = this.db.select({
      name: sqliteMaster.name,
      sql: sqliteMaster.sql,
    }).from(sqliteMaster).where(eq(sqliteMaster.type, 'table')).all();
    const applicationTables = catalog.filter((row) => (
      typeof row.name === 'string'
      && !row.name.startsWith('sqlite_')
      && row.name !== '__drizzle_migrations'
    ));
    const journalExists = catalog.some((row) => row.name === '__drizzle_migrations');
    const recordedMigrations = journalExists ? this.db.select().from(drizzleMigrations).all() : [];
    if (!applicationTables.length) {
      migrate(this.db, { migrationsFolder: MIGRATIONS_DIR });
      return;
    }
    if (recordedMigrations.length) {
      migrate(this.db, { migrationsFolder: MIGRATIONS_DIR });
      return;
    }

    // Drizzle creates its journal through the migrator. An empty metadata-only
    // migration set gives legacy databases that same setup without embedding
    // schema DDL in application code.
    if (!journalExists) {
      migrate(this.db, { migrationsFolder: BOOTSTRAP_MIGRATIONS_DIR });
    }

    const migrationFiles = readMigrationFiles({ migrationsFolder: MIGRATIONS_DIR });
    const migrationJournal = JSON.parse(fs.readFileSync(
      path.join(MIGRATIONS_DIR, 'meta', '_journal.json'), 'utf8',
    )) as MigrationJournal;
    const migrationSnapshots = migrationJournal.entries.map(({ idx }) => JSON.parse(fs.readFileSync(
      path.join(MIGRATIONS_DIR, 'meta', `${String(idx).padStart(4, '0')}_snapshot.json`), 'utf8',
    )) as MigrationSnapshot);
    const appliedCount = this.inferMigrationCount(catalog, migrationSnapshots);
    this.db.insert(drizzleMigrations).values(migrationFiles.slice(0, appliedCount).map((migration) => ({
      hash: migration.hash,
      createdAt: migration.folderMillis,
    }))).run();
    migrate(this.db, { migrationsFolder: MIGRATIONS_DIR });
  }

  private inferMigrationCount(
    catalog: Array<{ name: string | null; sql: string | null }>,
    snapshots: MigrationSnapshot[],
  ): number {
    const definitions = new Map(catalog.map((row) => [row.name, row.sql ?? '']));
    const matches = (snapshot: MigrationSnapshot): boolean => Object.entries(snapshot.tables).every(([tableName, table]) => {
      const definition = definitions.get(tableName);
      if (definition === undefined) return false;
      return Object.keys(table.columns).every((columnName) => (
        new RegExp(`\\b${columnName}\\b`).test(definition)
      ));
    });
    for (let index = snapshots.length - 1; index >= 0; index -= 1) {
      if (matches(snapshots[index])) return index + 1;
    }
    throw new Error('The database schema does not match a supported Shoplist migration.');
  }

  /**
   * Operation outcomes are retained indefinitely. A list session can remain
   * open across an arbitrarily long outage, including after a list deletion,
   * so time-based pruning would make a replay unsafe. The processed table is
   * intentionally the durable replay window; a future bounded policy must be
   * paired with a maximum live-session lifetime.
   */
  private cleanupProcessedOperations(): void {
    // Deliberately empty: indefinite retention is the current replay policy.
  }

  /** Reload the in-memory compatibility view from the Drizzle tables. */
  public load(): void {
    const listRows = this.db.select().from(schema.lists).all();
    const itemRows = this.db.select().from(schema.items).all();
    const memberRows = this.db.select().from(schema.members).all();
    const itemsByList = new Map<string, ShoppingItem[]>();
    const membersByList = new Map<string, Record<string, Member>>();

    for (const row of itemRows) {
      const listItems = itemsByList.get(row.listId) || [];
      listItems.push({
        id: row.id,
        name: row.name,
        amount: row.amount,
        collected: Boolean(row.collected),
        createdAt: row.createdAt,
        updatedAt: row.updatedAt,
        by: row.by ?? null,
        lastEditedBy: row.lastEditedBy ?? null,
      });
      itemsByList.set(row.listId, listItems);
    }

    for (const row of memberRows) {
      const listMembers = membersByList.get(row.listId) || {};
      listMembers[row.clientId] = {
        clientId: row.clientId,
        name: row.name,
        color: row.color,
        joinedAt: row.joinedAt,
        leftAt: row.leftAt ?? null,
      };
      membersByList.set(row.listId, listMembers);
    }

    const lists: Record<string, ShoppingList> = {};
    for (const row of listRows) {
      lists[row.id] = {
        id: row.id,
        name: row.name,
        ownerToken: row.ownerToken,
        createdAt: row.createdAt,
        clearedAt: row.clearedAt ?? null,
        revision: row.revision ?? 0,
        items: itemsByList.get(row.id) || [],
        members: membersByList.get(row.id) || {},
      };
    }
    this.data = { lists };
  }

  public listCount(): number {
    return Object.keys(this.data.lists).length;
  }

  public flushSync(): void {
    if (this.closed) return;
    try {
      this.sqlite.pragma('wal_checkpoint(TRUNCATE)');
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      console.error('[store] checkpoint failed:', message);
    }
  }

  public close(): void {
    if (this.closed) return;
    this.flushSync();
    this.sqlite.close();
    this.closed = true;
  }

  // ------------------------------------------------------------- lists

  public createList(name: unknown): ShoppingList {
    const now = Date.now();
    const list: ShoppingList = {
      id: rid(9),
      name: cleanText(name, 60) || 'Shopping list',
      ownerToken: rid(12),
      createdAt: now,
      clearedAt: null,
      revision: 0,
      items: [],
      members: {},
    };

    this.db.insert(schema.lists).values({
      id: list.id,
      name: list.name,
      ownerToken: list.ownerToken,
      createdAt: list.createdAt,
      clearedAt: list.clearedAt,
    }).run();
    this.data.lists[list.id] = list;
    return list;
  }

  public getList(id: string | undefined): ShoppingList | null {
    return (id && this.data.lists[id]) || null;
  }

  public deleteList(id: string): boolean {
    if (!this.data.lists[id]) return false;
    const result = this.db.delete(schema.lists).where(eq(schema.lists.id, id)).run();
    if (result.changes === 0) return false;
    delete this.data.lists[id];
    return true;
  }

  public renameList(list: ShoppingList, name: unknown): boolean {
    const clean = cleanText(name, 60);
    if (!clean) return false;
    const result = this.db.update(schema.lists)
      .set({ name: clean })
      .where(eq(schema.lists.id, list.id))
      .run();
    if (result.changes === 0) return false;
    list.name = clean;
    return true;
  }

  public clearList(list: ShoppingList): void {
    const clearedAt = Date.now();
    this.db.transaction((tx) => {
      tx.delete(schema.items).where(eq(schema.items.listId, list.id)).run();
      tx.update(schema.lists)
        .set({ clearedAt })
        .where(eq(schema.lists.id, list.id))
        .run();
    });
    list.items = [];
    list.clearedAt = clearedAt;
  }

  public touchMember(list: ShoppingList, clientId: string, name: string, color: string): { joined: boolean } {
    const existing = list.members[clientId];
    const joined = !existing || existing.leftAt !== null;
    const cleanName = cleanText(name, 40) || 'Guest';
    const member = {
      listId: list.id,
      clientId,
      name: cleanName,
      color,
      joinedAt: existing?.joinedAt || Date.now(),
      leftAt: null,
    };

    this.db.insert(schema.members)
      .values(member)
      .onConflictDoUpdate({
        target: [schema.members.listId, schema.members.clientId],
        set: { name: member.name, color: member.color, leftAt: null },
      })
      .run();
    list.members[clientId] = {
      clientId,
      name: member.name,
      color: member.color,
      joinedAt: member.joinedAt,
      leftAt: null,
    };
    return { joined };
  }

  public leaveMember(listId: string, clientId: string): boolean {
    const list = this.data.lists[listId];
    const member = list?.members[clientId];
    if (!member || member.leftAt !== null) return false;
    const leftAt = Date.now();
    const result = this.db.update(schema.members)
      .set({ leftAt })
      .where(and(eq(schema.members.listId, listId), eq(schema.members.clientId, clientId)))
      .run();
    if (result.changes === 0) return false;
    member.leftAt = leftAt;
    return true;
  }

  public memberCount(list: ShoppingList): number {
    return Object.keys(list.members || {}).length;
  }

  public getNotificationStatus(listId: string, clientId: string): { enabled: boolean; muted: boolean } {
    const member = this.data.lists[listId]?.members[clientId];
    if (!member || member.leftAt !== null) return { enabled: false, muted: false };
    const destination = this.db.select().from(schema.pushDestinations)
      .where(and(eq(schema.pushDestinations.listId, listId), eq(schema.pushDestinations.clientId, clientId)))
      .get();
    return { enabled: Boolean(destination), muted: Boolean(destination?.muted) };
  }

  public registerPushDestination(listId: string, clientId: string, subscription: PushSubscription): boolean {
    const member = this.data.lists[listId]?.members[clientId];
    if (!member || member.leftAt !== null) return false;
    const now = Date.now();
    this.db.insert(schema.pushDestinations).values({
      listId,
      clientId,
      endpoint: subscription.endpoint,
      p256dh: subscription.keys.p256dh,
      auth: subscription.keys.auth,
      createdAt: now,
      updatedAt: now,
    }).onConflictDoUpdate({
      target: [schema.pushDestinations.listId, schema.pushDestinations.clientId],
      set: {
        endpoint: subscription.endpoint,
        p256dh: subscription.keys.p256dh,
        auth: subscription.keys.auth,
        updatedAt: now,
      },
    }).run();
    return true;
  }

  public setNotificationsMuted(listId: string, clientId: string, muted: boolean): boolean {
    const result = this.db.update(schema.pushDestinations)
      .set({ muted, updatedAt: Date.now() })
      .where(and(eq(schema.pushDestinations.listId, listId), eq(schema.pushDestinations.clientId, clientId)))
      .run();
    return result.changes > 0;
  }

  public getNotificationRecipients(listId: string, onlineClientIds: Set<string>): PushDestination[] {
    const list = this.data.lists[listId];
    if (!list) return [];
    const destinations = this.db.select().from(schema.pushDestinations)
      .where(eq(schema.pushDestinations.listId, listId)).all();
    return destinations
      .filter((destination) => {
        const member = list.members[destination.clientId];
        return Boolean(member && member.leftAt === null && !destination.muted && !onlineClientIds.has(destination.clientId));
      })
      .map((destination) => ({
        listId: destination.listId,
        clientId: destination.clientId,
        endpoint: destination.endpoint,
        keys: { p256dh: destination.p256dh, auth: destination.auth },
        muted: Boolean(destination.muted),
      }));
  }

  public disableNotifications(listId: string, clientId: string): boolean {
    const result = this.db.delete(schema.pushDestinations)
      .where(and(
        eq(schema.pushDestinations.listId, listId),
        eq(schema.pushDestinations.clientId, clientId),
      )).run();
    return result.changes > 0;
  }

  public removePushDestination(listId: string, clientId: string, endpoint: string): boolean {
    const result = this.db.delete(schema.pushDestinations)
      .where(and(
        eq(schema.pushDestinations.listId, listId),
        eq(schema.pushDestinations.clientId, clientId),
        eq(schema.pushDestinations.endpoint, endpoint),
      )).run();
    return result.changes > 0;
  }

  // ------------------------------------------------------------- items

  public addItem(list: ShoppingList, { name, amount }: NewItem, by: string | null): ShoppingItem | null {
    const cleanName = cleanText(name, 80);
    if (!cleanName) return null;
    const now = Date.now();
    const item: ShoppingItem = {
      id: rid(8),
      name: cleanName,
      amount: cleanText(amount, 40),
      collected: false,
      createdAt: now,
      updatedAt: now,
      by: by || null,
      lastEditedBy: by || null,
    };

    this.db.insert(schema.items).values({
      id: item.id,
      listId: list.id,
      name: item.name,
      amount: item.amount,
      collected: item.collected,
      createdAt: item.createdAt,
      updatedAt: item.updatedAt,
      by: item.by,
      lastEditedBy: item.lastEditedBy,
    }).run();
    list.items.push(item);
    return item;
  }

  public updateItem(list: ShoppingList, itemId: string, patch: ItemPatch, actorClientId: string | null = null): boolean {
    const item = list.items.find((candidate) => candidate.id === itemId);
    if (!item) return false;

    const values: Partial<typeof schema.items.$inferInsert> = { updatedAt: Date.now() };
    if (patch.name !== undefined) {
      const clean = cleanText(patch.name, 80);
      if (!clean) return false; // an item always keeps a name
      values.name = clean;
    }
    if (patch.amount !== undefined) values.amount = cleanText(patch.amount, 40);
    if (patch.collected !== undefined) values.collected = Boolean(patch.collected);
    if (Object.keys(values).length === 1) return false;
    if (actorClientId) values.lastEditedBy = actorClientId;

    const result = this.db.update(schema.items)
      .set(values)
      .where(and(eq(schema.items.id, itemId), eq(schema.items.listId, list.id)))
      .run();
    if (result.changes === 0) return false;

    if (values.name !== undefined) item.name = values.name;
    if (values.amount !== undefined) item.amount = values.amount;
    if (values.collected !== undefined) item.collected = values.collected;
    item.updatedAt = values.updatedAt as number;
    if (values.lastEditedBy !== undefined) item.lastEditedBy = values.lastEditedBy;
    return true;
  }

  public deleteItem(list: ShoppingList, itemId: string): boolean {
    const result = this.db.delete(schema.items)
      .where(and(eq(schema.items.id, itemId), eq(schema.items.listId, list.id)))
      .run();
    if (result.changes === 0) return false;
    const index = list.items.findIndex((item) => item.id === itemId);
    if (index !== -1) list.items.splice(index, 1);
    return true;
  }

  // ------------------------------------------------------------- operation stream

  /**
   * Apply one idempotent websocket operation. The list mutation, revision, and
   * original acknowledgement are committed in one SQLite transaction.
   */
  public applyOperation(listId: string, operation: StoreOperation): OperationResult {
    const current = this.getList(listId);
    const operationId = typeof operation.operationId === 'string' ? operation.operationId : '';
    const payloadHash = operation.protocolVersion === 1 ? operationFingerprint(operation) : undefined;
    if (operationId) {
      const stored = this.db.select().from(schema.processedOperations)
        .where(and(
          eq(schema.processedOperations.listId, listId),
          eq(schema.processedOperations.operationId, operationId),
        )).get();
      if (stored) {
        const list = this.getList(listId);
        if (payloadHash && stored.payloadHash && stored.payloadHash !== payloadHash) {
          return {
            ack: rejected(operation, list?.revision ?? stored.revision, 'operation-id-reused', 'The Operation ID was already used for a different mutation.'),
            list,
            duplicate: false,
            terminal: false,
          };
        }
        return {
          ack: JSON.parse(stored.responseJson) as OperationAck,
          list,
          duplicate: true,
          terminal: Boolean(stored.terminal),
        };
      }
    }
    const deletionRecipients = current && operation.kind === 'list:delete'
      ? this.getNotificationRecipients(listId, new Set()) : undefined;
    if (!operationId || operationId.length > 160) {
      const safeOperation = { ...operation, operationId } as StoreOperation;
      const ack = rejected(safeOperation, current?.revision ?? 0, 'operation-too-large', 'The operation ID is invalid.');
      if (operationId) {
        this.db.insert(schema.processedOperations).values({
          listId,
          operationId,
          status: ack.status,
          revision: ack.revision,
          responseJson: JSON.stringify(ack),
          payloadHash,
          terminal: false,
          processedAt: Date.now(),
        }).run();
      }
      return { ack, list: current, duplicate: false, terminal: false };
    }

    if (!OPERATION_KINDS.includes(operation.kind) || !isRecordValue(operation.payload)) {
      const ack = rejected(operation, current?.revision ?? 0, 'invalid-operation', 'The operation is not supported.');
      this.db.insert(schema.processedOperations).values({
        listId,
        operationId: operation.operationId,
        status: ack.status,
        revision: ack.revision,
        responseJson: JSON.stringify(ack),
        payloadHash,
        terminal: false,
        processedAt: Date.now(),
      }).run();
      return { ack, list: current, duplicate: false, terminal: false };
    }

    const now = Date.now();
    const result = this.db.transaction((tx) => {
      const list = current;
      const revision = list?.revision ?? 0;
      let ack: OperationAck;
      let terminal = false;
      let accepted = false;
      let changedItem: ShoppingItem | null = null;
      let deletedItemId: string | null = null;
      let clearAt: number | null = null;
      let renamedTo: string | null = null;
      let notification: NotificationEvent | undefined;

      if (!list) {
        ack = {
          t: 'ack', opId: operation.operationId, status: 'rejected',
          revision, reason: 'list-not-found', reasonCode: 'list-not-found',
          message: 'The list no longer exists.',
        };
      } else {
        switch (operation.kind) {
          case 'item:add': {
            const itemPayload = isRecordValue(operation.payload.item) ? operation.payload.item : operation.payload;
            if (itemPayload.name !== undefined && typeof itemPayload.name !== 'string') {
              ack = rejected(operation, revision, 'invalid-payload', 'The item name is invalid.');
              break;
            }
            if (itemPayload.amount !== undefined && typeof itemPayload.amount !== 'string') {
              ack = rejected(operation, revision, 'invalid-payload', 'The item amount is invalid.');
              break;
            }
            const name = cleanText(itemPayload.name, 80);
            if (!name) {
              ack = rejected(operation, revision, 'name-required', 'An item needs a name.');
              break;
            }
            const item: ShoppingItem = {
              id: rid(8),
              name,
              amount: cleanText(itemPayload.amount, 40),
              collected: false,
              createdAt: now,
              updatedAt: now,
              by: operation.actorClientId || null,
              lastEditedBy: operation.actorClientId || null,
            };
            const nextRevision = revision + 1;
            tx.insert(schema.items).values({
              id: item.id, listId, name: item.name, amount: item.amount,
              collected: item.collected, createdAt: item.createdAt,
              updatedAt: item.updatedAt, by: item.by, lastEditedBy: item.lastEditedBy,
            }).run();
            ack = {
              t: 'ack', opId: operation.operationId, status: 'accepted',
              revision: nextRevision, item, itemId: item.id,
              tempItemId: stringValue(itemPayload.tempItemId) || stringValue(itemPayload.tempId),
              idMap: stringValue(itemPayload.tempItemId) || stringValue(itemPayload.tempId)
                ? { tempId: (stringValue(itemPayload.tempItemId) || stringValue(itemPayload.tempId)) as string, itemId: item.id }
                : undefined,
            };
            accepted = true;
            changedItem = item;
            break;
          }

          case 'item:update': {
            const itemId = stringValue(operation.payload.id);
            const item = itemId ? list.items.find((candidate) => candidate.id === itemId) : undefined;
            const patchValue = operation.payload.patch;
            if (!item || !isRecordValue(patchValue)) {
              ack = rejected(operation, revision, 'item-not-found', 'The item no longer exists.');
              break;
            }
            const patch: ItemPatch = {};
            if ('name' in patchValue) patch.name = patchValue.name;
            if ('amount' in patchValue) patch.amount = patchValue.amount;
            if ('collected' in patchValue) patch.collected = patchValue.collected;
            if (patch.name !== undefined && typeof patch.name !== 'string') {
              ack = rejected(operation, revision, 'invalid-payload', 'The item name is invalid.');
              break;
            }
            if (patch.amount !== undefined && typeof patch.amount !== 'string') {
              ack = rejected(operation, revision, 'invalid-payload', 'The item amount is invalid.');
              break;
            }
            if (patch.collected !== undefined && typeof patch.collected !== 'boolean') {
              ack = rejected(operation, revision, 'invalid-payload', 'The collected state is invalid.');
              break;
            }
            const values: Partial<typeof schema.items.$inferInsert> = { updatedAt: now };
            if (patch.name !== undefined) {
              const clean = cleanText(patch.name, 80);
              if (!clean) {
                ack = rejected(operation, revision, 'name-required', 'An item needs a name.');
                break;
              }
              values.name = clean;
            }
            if (patch.amount !== undefined) values.amount = cleanText(patch.amount, 40);
            if (patch.collected !== undefined) values.collected = Boolean(patch.collected);
            if (Object.keys(values).length === 1) {
              ack = rejected(operation, revision, 'invalid-payload', 'No item fields were supplied.');
              break;
            }
            if (operation.actorClientId) values.lastEditedBy = operation.actorClientId;
            tx.update(schema.items).set(values)
              .where(and(eq(schema.items.id, item.id), eq(schema.items.listId, listId))).run();
            changedItem = { ...item };
            if (values.name !== undefined) changedItem.name = values.name;
            if (values.amount !== undefined) changedItem.amount = values.amount;
            if (values.collected !== undefined) changedItem.collected = values.collected;
            if (values.lastEditedBy !== undefined) changedItem.lastEditedBy = values.lastEditedBy;
            changedItem.updatedAt = now;
            ack = {
              t: 'ack', opId: operation.operationId, status: 'accepted',
              revision: revision + 1, itemId: item.id,
            };
            accepted = true;
            break;
          }

          case 'item:delete': {
            const itemId = stringValue(operation.payload.id);
            const item = itemId ? list.items.find((candidate) => candidate.id === itemId) : undefined;
            if (!item) {
              ack = rejected(operation, revision, 'item-not-found', 'The item no longer exists.');
              break;
            }
            tx.delete(schema.items).where(and(eq(schema.items.id, item.id), eq(schema.items.listId, listId))).run();
            ack = {
              t: 'ack', opId: operation.operationId, status: 'accepted', revision: revision + 1,
              itemId: item.id,
            };
            accepted = true;
            deletedItemId = item.id;
            break;
          }

          case 'list:clear':
            clearAt = now;
            tx.delete(schema.items).where(eq(schema.items.listId, listId)).run();
            tx.update(schema.lists).set({ clearedAt: clearAt, revision: revision + 1 })
              .where(eq(schema.lists.id, listId)).run();
            ack = { t: 'ack', opId: operation.operationId, status: 'accepted', revision: revision + 1 };
            accepted = true;
            break;

          case 'list:rename': {
            if (operation.payload.name !== undefined && typeof operation.payload.name !== 'string') {
              ack = rejected(operation, revision, 'invalid-payload', 'The list name is invalid.');
              break;
            }
            const name = cleanText(operation.payload.name, 60);
            if (!name) {
              ack = rejected(operation, revision, 'name-required', 'Give the list a name.');
              break;
            }
            tx.update(schema.lists).set({ name, revision: revision + 1 })
              .where(eq(schema.lists.id, listId)).run();
            ack = { t: 'ack', opId: operation.operationId, status: 'accepted', revision: revision + 1 };
            accepted = true;
            renamedTo = name;
            break;
          }

          case 'list:delete':
            if (stringValue(operation.payload.ownerToken) !== list.ownerToken) {
              ack = rejected(operation, revision, 'not-owner', 'Only the list owner can delete it.');
              break;
            }
            // The outcome is intentionally not foreign-keyed to lists. It must
            // remain replayable after the list row and its children disappear.
            ack = { t: 'ack', opId: operation.operationId, status: 'accepted', revision: revision + 1 };
            tx.delete(schema.lists).where(eq(schema.lists.id, listId)).run();
            accepted = true;
            terminal = true;
            break;
        }
      }

      if (list && accepted && operation.kind !== 'list:clear' && operation.kind !== 'list:rename' && operation.kind !== 'list:delete') {
        tx.update(schema.lists).set({ revision: revision + 1 }).where(eq(schema.lists.id, listId)).run();
      }
      if (list && accepted) {
        const kind = operation.kind === 'list:clear' ? 'clear'
          : operation.kind === 'list:rename' ? 'rename'
            : operation.kind === 'list:delete' ? 'delete' : 'changed';
        notification = {
          listId,
          listName: renamedTo || list.name,
          actorClientId: operation.actorClientId || '',
          actorName: cleanText(operation.actorName, 40) || 'Someone',
          kind,
        };
      }
      tx.insert(schema.processedOperations).values({
        listId,
        operationId: operation.operationId,
        status: ack.status,
        revision: ack.revision,
        responseJson: JSON.stringify(ack),
        payloadHash,
        terminal,
        processedAt: now,
      }).run();
      return { ack, accepted, terminal, changedItem, deletedItemId, clearAt, renamedTo, notification, notificationRecipients: deletionRecipients };
    });

    // Only update the compatibility projection after the transaction commits.
    if (current && result.accepted) {
      if (operation.kind === 'list:delete') {
        delete this.data.lists[listId];
      } else {
        current.revision = result.ack.revision;
        if (result.changedItem) {
          const index = current.items.findIndex((item) => item.id === result.changedItem!.id);
          if (index === -1) current.items.push(result.changedItem);
          else current.items[index] = result.changedItem;
        }
        if (result.deletedItemId) current.items = current.items.filter((item) => item.id !== result.deletedItemId);
        if (result.clearAt !== null) {
          current.items = [];
          current.clearedAt = result.clearAt;
        }
        if (result.renamedTo !== null) current.name = result.renamedTo;
      }
    }
    return {
      ack: result.ack,
      list: this.getList(listId),
      duplicate: false,
      terminal: result.terminal,
      notification: result.notification,
      notificationRecipients: result.notificationRecipients,
    };
  }

}

function isRecordValue(value: unknown): value is Record<string, unknown> {
  return Boolean(value && typeof value === 'object' && !Array.isArray(value));
}

function stringValue(value: unknown): string | undefined {
  return typeof value === 'string' && value.length > 0 ? value : undefined;
}

function operationFingerprint(operation: StoreOperation): string {
  const canonical = (value: unknown): unknown => {
    if (Array.isArray(value)) return value.map(canonical);
    if (value && typeof value === 'object') {
      return Object.fromEntries(Object.entries(value as Record<string, unknown>)
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([key, nested]) => [key, canonical(nested)]));
    }
    return value;
  };
  return createHash('sha256').update(JSON.stringify(canonical({
    kind: operation.kind,
    payload: operation.payload,
    actorClientId: operation.actorClientId,
  }))).digest('hex');
}

function rejected(operation: StoreOperation, revision: number, reason: string, message: string): OperationAck {
  return {
    t: 'ack', opId: operation.operationId, status: 'rejected', revision,
    reason, reasonCode: reason, message,
  };
}
